module.exports = {
  TIME_STEP: 50,
  SERVER_MAX_TICK: 2000,
  GAME_ID_POOL_SIZE: 256,

  GAME_FIELD_SIZE: { x: 100, y: 100 },
  PLAYER_SIZE: 1,
  ADDITIONAL_SPAWN_DISTANCE: 1,

  PLAYER_SPEED: 0.1,
  MIN_ROTATION_SPEED: 0.02,
  MAX_ROTATION_SPEED: Math.PI / 40
};
